### ISSUE TITLE
make build produces 'invalid syntax' error

### ISSUE THREAD

**Issue by m88614** [fredrikhgrelland/vagrant-hashistack#1]
Steps to reproduce:
1. Run `make install`
2. Run `make build` with the stanza `post-processor "vagrant-cloud"` in `hashistak.pkr.hcl` commented out.
![image](https://user-images.githubusercontent.com/51820995/83236329-a47ad800-a193-11ea-845c-ad8a5da20514.png)

**Comment by fredrikhgrelland** [comment]
Caused by transparent proxy. SSL error.
