### ISSUE TITLE
Support and create template for packaging _and_ using terraform module in test.

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#102]
https://github.com/fredrikhgrelland/docker-hive/issues/23

**Comment by fredrikhgrelland** [comment]
The template should make it easy to design and build a terraform module. That module should be used to test the service. We need to build a module in the example.

**Comment by pdmthorsrud** [comment]
I'll start looking at this, but at first glance I don't see much that needs changing except doc. Do you have any specific requirements in mind, @fredrikhgrelland?

**Comment by fredrikhgrelland** [comment]
In order for the template to be used as a terraform module directly, it needs to follow a strict set of rules.
https://www.terraform.io/docs/modules/index.html#standard-module-structure

**Comment by zhenik** [comment]
docker-hive ref https://github.com/fredrikhgrelland/docker-hive/issues/23#issuecomment-653011849
