### ISSUE TITLE
Template is not practical and not complete.

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#133]
Trying to use the template to refactor fredrikhgrelland/docker-presto I have found that it is not working just yet. And needs some attantion to documentation and keeping it DRY.

**Comment by zhenik** [comment]
Could you elaborate about the major problem(s)?

**Comment by fredrikhgrelland** [comment]
I am in the process of finding it out, but some findings:
- test directory should not include all configurations and artifacts but should override if necessary.
- Currently you must copy the same artifacts in root and test dir. Not practical.
