### ISSUE TITLE
'vagrant box update' throws error 'error setting certificate verify locations:'

### ISSUE THREAD

**Issue by m88614** [fredrikhgrelland/vagrant-hashistack#135]
Getting an error when trying to update the box. I am not behind a transparent proxy. This might very well just be me in a post-vacation haze, but in worst case the issue can serve as a help to others. Updating when I find the solution.

![image](https://user-images.githubusercontent.com/51820995/87398647-7708b300-c5b6-11ea-8021-3519700bc3a5.png)
![image](https://user-images.githubusercontent.com/51820995/87399109-2b0a3e00-c5b7-11ea-9dbb-eb377551384e.png)

**Comment by m88614** [comment]
So this issue came up because I had the env variables SSL_CERT_FILE and CURL_CA_BUNDLE set, but I am NOT behind a transparent proxy. Unset them and it works. 
![image](https://user-images.githubusercontent.com/51820995/87407074-f18b0000-c5c1-11ea-8c10-50d96cc09ba5.png)

**Comment by zhenik** [comment]
@m88614  can we close this issue?

**Comment by m88614** [comment]
> @m88614 can we close this issue?

Oops, yeah. Closing!
