### ISSUE TITLE
Make `build` fail 

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#136]
## Steps to reproduce
It happens on new VDIs. 
People faced with it: @AditiSharma77 and @nsinha17 

## Log
```
$ make build
(cd packer; rm -rf output-hashistack; packer build -force .)
vagrant.hashistack: output will be in this color.

==> vagrant.hashistack: Creating a Vagrantfile in the build directory...
==> vagrant.hashistack: Adding box using vagrant box add ...
    vagrant.hashistack: (this can take some time if we need to download the box)
==> vagrant.hashistack: Calling Vagrant Up (this can take some time)...
==> vagrant.hashistack: destroying Vagrant box...
==> vagrant.hashistack: Deleting output directory...
Build 'vagrant.hashistack' errored: strconv.Atoi: parsing "": invalid syntax

==> Some builds didn't complete successfully and had errors:
--> vagrant.hashistack: strconv.Atoi: parsing "": invalid syntax

==> Builds finished but no artifacts were created.
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by zhenik** [comment]
https://github.com/hashicorp/packer/issues/9564

**Comment by zhenik** [comment]
## Further investigation
`--debug` flag of vagrant cli, shows 
```
2020/07/15 11:13:19 packer-builder-vagrant plugin: [vagrant driver] stderr: Stderr: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
```

After installation of `vboxmanage` could not find provider, (provider VirtualBox was installed but not loaded). 
The reason was that VDI has not enabled virtualization

## Check virtualisation
`lscpu` -> verify that virtualisation is enabled.

**Comment by m88614** [comment]
Seems like this should not be a problem on MacOS. Searching for a way to enable virtualisation I get this (page)[https://support.apple.com/en-us/HT203296} that suggests it should be enabled by default. I'll update the README to include info about virtualization

**Comment by m88614** [comment]
@zhenik Can we close this issue, considering this is not something we can fix?

**Comment by zhenik** [comment]
> @zhenik Can we close this issue, considering this is not something we can fix?

@AditiSharma77 could follow this thread, please.

**Comment by AditiSharma77** [comment]
I think we can close this issue . Agree https://github.com/fredrikhgrelland/vagrant-hashistack/issues/139
