### ISSUE TITLE
Update README: "What is error 'VT-x not enabled'"

### ISSUE THREAD

**Issue by m88614** [fredrikhgrelland/vagrant-hashistack#139]
#136 details an error where virtualisation is not enabled. Add a section to README that explains the problem.

**Comment by m88614** [comment]
What do you guys think, is this something we should add? It is not a problem with the repo, but rather the user's machine, but it is still a problem several might end up having.

**Comment by zhenik** [comment]
I think it would be nice to have a readme chapter with computer requirements (OS, virtualization enabled, etc...)

**Comment by m88614** [comment]
> I think it would be nice to have a readme chapter with computer requirements (OS, virtualization enabled, etc...)

Yeah, that's a good idea. I'll add that. :)

**Comment by m88614** [comment]
Closing. #141 fixed it, forgot to link it before merging PR
