### ISSUE TITLE
Ansible pre and poststart books are NOT loaded lexically

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#143]
Books in prestart and poststart folders are not loaded lexically. `with_fileglob` which is used to run the plays does not support lexical order. Could potentially do something like this: https://stackoverflow.com/questions/59162054/how-to-run-ansible-with-fileglob-in-alpabetical-order.

This should have printed `hello1`, `hello2`, `This would be a prestart task`
<img width="353" alt="Screenshot 2020-07-22 at 11 34 14" src="https://user-images.githubusercontent.com/51820995/88160734-5f14dd00-cc0f-11ea-8857-8b66ec0a198a.png">
<img width="215" alt="image" src="https://user-images.githubusercontent.com/51820995/88160790-718f1680-cc0f-11ea-8b02-98bab3d0dfb7.png">

**Comment by fredrikhgrelland** [comment]
I will fix :)
