### ISSUE TITLE
Get rid of `dev` mode

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#150]

**Comment by fredrikhgrelland** [comment]
Why?

**Comment by zhenik** [comment]
> Why?

![100](https://user-images.githubusercontent.com/15572799/89276587-1cf28f00-d644-11ea-9174-7e7b338033b0.PNG)

**Comment by fredrikhgrelland** [comment]
Ok- let us rephrase that statement. We want it to run in dev mode.
