### ISSUE TITLE
Enable matrix testing via github actions

### ISSUE THREAD

**Issue by Neha-Sinha2305** [fredrikhgrelland/vagrant-hashistack#152]
The task is to enable matrix testing via github actions. The first and foremost changes will be done with regards to running tests when _consul_agent_acl_default_policy_ is set to either **allow** or **deny**.

**Comment by fredrikhgrelland** [comment]
Any updates on this?

**Comment by Neha-Sinha2305** [comment]
I have created a PR with the code changes.

**Comment by fredrikhgrelland** [comment]
closing #167
