### ISSUE TITLE
ansible poststart runs before terraform starts jobs in nomad.

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#154]
Is this really the intended workflow?

**Comment by pdmthorsrud** [comment]
No, it makes more sense for it to start after the hashistack. Maybe change name to pre- and post_hashi?

**Comment by zhenik** [comment]
I agree with @pdmthorsrud 

prestart -> up consul, nomad, vault -> poststart -> terraform

**Comment by fredrikhgrelland** [comment]
ok :)
