### ISSUE TITLE
Get rid of `awk` and `grep` in ansible playbooks -> `jq` instead

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#159]

**Comment by fredrikhgrelland** [comment]
Additionally: there is actually no need to do json-pathing with jq in ansible. If the output is json, you may use the "register"-ed variable directly. BUT for cli I _like_ to use a complete command for testability and readability.

**Comment by zhenik** [comment]
issue is irelevant
