### ISSUE TITLE
Make consul ACL toggle follow same pattern as Nomad ACL toggle

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#163]
There is a new pattern in #160, ACL toggle should use the same pattern. Need to update README as well.

**Comment by fredrikhgrelland** [comment]
@pdmthorsrud closes #167 ?

**Comment by pdmthorsrud** [comment]
> @pdmthorsrud closing #167 ?

Yup! 😄
