### ISSUE TITLE
Fix linting issues in bootstrap.yml

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#164]
Some of the lines in bootstrap.yml are too long. Can be fixed with [folding](https://stackoverflow.com/questions/53098493/how-to-nicely-split-on-multiple-lines-long-conditionals-with-or-on-ansible)
![image](https://user-images.githubusercontent.com/51820995/89630346-87ebd200-d89f-11ea-80bf-ea27ec6344c4.png)

**Comment by fredrikhgrelland** [comment]
folding :+1:

**Comment by pdmthorsrud** [comment]
After removing the error it does not throw the warnings anymore. Any idea why?

**Comment by fredrikhgrelland** [comment]
No.. Strange. Only thing I see is that the default apparently was updated from 80 to 160 lines long..

**Comment by fredrikhgrelland** [comment]
In any case we should use the folding operator where that makes sense.

**Comment by pdmthorsrud** [comment]
> No.. Strange. Only thing I see is that the default apparently was updated from 80 to 160 lines long..

Wait, you're saying it was indeed changed, or that it could explain why it isn't throwing the error?
