### ISSUE TITLE
Add documentation to give a comprehensive overview of the default configuration used for setting up the system

### ISSUE THREAD

**Issue by Neha-Sinha2305** [fredrikhgrelland/vagrant-hashistack#165]
The documentation will innhold the following information :

- Default configurations with which the sytstem is set up
- How the default configurations can be overriden to create a system that serves the developmet needs
- Test scenarios that are currently executed to qualify the system

**Comment by Neha-Sinha2305** [comment]
@fredrikhgrelland : What else do you think would be relevant to have in the document?

**Comment by fredrikhgrelland** [comment]
I think this is i good starting point. Additional docs will be relevant in context of the template, but we are not there yet..

**Comment by fredrikhgrelland** [comment]
@Neha-Sinha2305 Should this be split after #168
