### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by Neha-Sinha2305** [fredrikhgrelland/vagrant-hashistack#170]
The matrix testing strategy builds the system under test with the following combination of nomad and consul acl values:

1. ~~test (consul_acl_enabled, consul_acl_allow, nomad_acl_enabled)~~
2. ~~test (consul_acl_enabled, consul_acl_allow, nomad_acl_disabled)~~
3. test (consul_acl_enabled, consul_acl_deny, nomad_acl_enabled)
4. test (consul_acl_enabled, consul_acl_deny, nomad_acl_disabled)
5. test (consul_acl_disabled, consul_acl_allow, nomad_acl_enabled)
6. test (consul_acl_disabled, consul_acl_allow, nomad_acl_disabled)

The task is to figure out if we have tests that cover each of the above mentioned combinations/paths. Also, it will be better to add these tests in a separate file(move them out of the bootstrap.yml) so that it is easier to locate them.

Currently we have tests that cover combinations 3 and 4 , however we are missing tests for 1, 2.

**Comment by Neha-Sinha2305** [comment]
@pdmthorsrud : Does this [main.tf](https://github.com/Neha-Sinha2305/vagrant-hashistack/blob/master/template/test/terraform/main.tf) cover both the cases when?
1. nomad_acl = true
2. nomad_acl = false

Also, does the following o/p from the test certifies that the job is running and is in healthy state? It says created so am not sure about the running state.

`nomad_job.countdash: Creating...
nomad_job.countdash: Still creating... [10s elapsed]
nomad_job.countdash: Still creating... [20s elapsed]
nomad_job.countdash: Still creating... [30s elapsed]
nomad_job.countdash: Creation complete after 35s [id=countdash]`

**Comment by pdmthorsrud** [comment]
> @pdmthorsrud : Does this [main.tf](https://github.com/Neha-Sinha2305/vagrant-hashistack/blob/master/template/test/terraform/main.tf) cover both the cases when?
> 
> 1. nomad_acl = true
> 2. nomad_acl = false
> 

I believe this covers acls on and off, yes. If ACLs are on, but not working properly this code would fail.

> Also, does the following o/p from the test certify that the job is running and is in healthy state? It says created so am not sure about the running state.
> 
> `nomad_job.countdash: Creating... nomad_job.countdash: Still creating... [10s elapsed] nomad_job.countdash: Still creating... [20s elapsed] nomad_job.countdash: Still creating... [30s elapsed] nomad_job.countdash: Creation complete after 35s [id=countdash]`

This indicates a job is running and healthy, correct. This task will **not** finish unless the task is healthy in nomad.

**Comment by Neha-Sinha2305** [comment]
@pdmthorsrud :Great! I wonder if it would be useful to add a negative test here like where we expect the terraform to fail when the nomad_acl is set to true?

**Comment by pdmthorsrud** [comment]
> @pdmthorsrud :Great! I wonder if it would be useful to add a negative test here like where we expect the terraform to fail when the nomad_acl is set to true?
> 
> 

I agree

**Comment by fredrikhgrelland** [comment]
> 
> > Also, does the following o/p from the test certify that the job is running and is in healthy state? It says created so am not sure about the running state.
> > `nomad_job.countdash: Creating... nomad_job.countdash: Still creating... [10s elapsed] nomad_job.countdash: Still creating... [20s elapsed] nomad_job.countdash: Still creating... [30s elapsed] nomad_job.countdash: Creation complete after 35s [id=countdash]`
> 
> This indicates a job is running and healthy, correct. This task will **not** finish unless the task is healthy in nomad.
This is only true if the job has a functioning **health check**. This example currently does not.

**Comment by pdmthorsrud** [comment]
> > This indicates a job is running and healthy, correct. This task will **not** finish unless the task is healthy in nomad.
> > This is only true if the job has a functioning **health check**. This example currently does not.

You are totally right.

I would also like to point out that this does indeed fail if nomad acls are not working properly, but are not testing that directly. This code will actually fail if there has been some error with writing the tokens to nomad or creating the roles, which CAN fail even though the nomad ACLs might be working the way they should.

**Comment by zhenik** [comment]
@fredrikhgrelland  @pdmthorsrud  @Neha-Sinha2305 Could we discuss case.1 and case.2  `(consul_acl_enabled, consul_acl_allow, ...)`

Is it realistic scenarios for setup when consul ACL enabled but default_policy=allow?

**Comment by pdmthorsrud** [comment]
> @fredrikhgrelland @pdmthorsrud @Neha-Sinha2305 Could we discuss case.1 and case.2 `(consul_acl_enabled, consul_acl_allow, ...)`
> 
> 1. Are these two realistic scenarios for setup, when consul ACL enabled but default_policy=allow?
> 2. In which case and how we should test these cases?

First thought is a case where you want to test and get to know nomad ACLs, without necessarilly having to handle other restrictions within the hashistack.

**Comment by Neha-Sinha2305** [comment]
1.I would like to answer this with a counter question : If this is not realistic scenario then why consul will have such a feature? They should only have the deny as the policy when acl is enabled.

**Comment by fredrikhgrelland** [comment]
We will never use default allow in a real world usecase, but it is very useful to be able to set it while using the box for development. e.g. intentions are enabled, but not enforced.

So - we do not need a test for allow, but we need a test to ensure acls are enabled and in use. I think you are right.. that leaves us with TESTING for acl_enabled(default_deny) and acl_disabled(whatever).

**Comment by Neha-Sinha2305** [comment]
> We will never use default allow in a real world usecase, but it is very useful to be able to set it while using the box for development. e.g. intentions are enabled, but not enforced.
> 
> So - we do not need a test for allow, but we need a test to ensure acls are enabled and in use. I think you are right.. that leaves us with TESTING for acl_enabled(default_deny) and acl_disabled(whatever).

Isn't **acl_disabled** the default configuration? Tests for this config could be skipped as we don not add any code to disable it so should work out of the box.

**Comment by Neha-Sinha2305** [comment]
So Case #1 and #2 have been removed from the test matrix.
