### ISSUE TITLE
Bad link `.env_override`

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#172]
Section in documentation https://github.com/fredrikhgrelland/vagrant-hashistack#test-configuration-and-execution 

![104](https://user-images.githubusercontent.com/15572799/89898790-97da1d80-dbe1-11ea-8a82-63851449451a.PNG)

**Comment by Neha-Sinha2305** [comment]
@fredrikhgrelland : Looks like we create the **.env_override** file on the fly when the github action is triggered, so i guess we need to get rid of the hyperlink from the documentation as it points to non-existing resource. Agree?

**Comment by pdmthorsrud** [comment]
> @fredrikhgrelland : Looks like we create the **.env_override** file on the fly when the github action is triggered, so i guess we need to get rid of the hyperlink from the documentation as it points to non-existing resource. Agree?

Yeah, that's right.
