### ISSUE TITLE
Add docker build to template

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#175]
Actually, it is a placeholder. We need to add build functionality to the template, as well as test functionality. This PR does not add that functionality, but we should add it soon

_Originally posted by @fredrikhgrelland in https://github.com/fredrikhgrelland/vagrant-hashistack/pull/174/review_comment/create_

**Comment by pdmthorsrud** [comment]
I assume you have started working on this, @fredrikhgrelland? I've worked a little on it, forgot to assign myself. Can you take this further, you have real experience from presto-docker :)

**Comment by fredrikhgrelland** [comment]
Yep. I'll create a draft PR for you to look at.
