### ISSUE TITLE
Box prints error when `.env_override` is not present

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#182]
The `.env_override` file is only generated by github-actions for testing, and will not be generated by normal use. Fix so that this prints a sensible message.
![image](https://user-images.githubusercontent.com/51820995/90006412-1cd43e00-dc99-11ea-808a-fc960ed8d934.png)

**Comment by fredrikhgrelland** [comment]
Fixed in #181
