### ISSUE TITLE
Find better way to create variables

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#199]
https://github.com/fredrikhgrelland/vagrant-hashistack/blob/f6bc0688a8e08fcbfa02bada1ea92365329d5272/ansible/install.yml#L148-L162

## Problem
`noise` variables like
```
TF_VAR_consul_enterprise
```
which are not in use

etc...

**Comment by fredrikhgrelland** [comment]
I agree. We should also refactor to use UPPER_CASE variables while we are at it.
Maybe also prefix `HASHISTACK_`?

**Comment by fredrikhgrelland** [comment]
> ## Problem
> `noise` variables like
> 
> ```
> TF_VAR_consul_enterprise
> ```
> 
> which are not in use
> 

This is not true.. We will want to have access to ALL switches in terraform, even if _we_ are not using it currently, the users of the box might.

**Comment by zhenik** [comment]
not relevant anymore
