### ISSUE TITLE
Tests performance - slow CD/CI

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#200]
Before, I have only heard about slow CD/CI because of tests.
Now, I witness it.

**Comment by Neha-Sinha2305** [comment]
If going forward our focus is to use enterprise version of hashistack to develop features then we can limit the number of tests that are run when a PR is created by running only tests valid for enterprise version.

We can add another workflow file that would run the complete set of tests(oss, enterprise ) nightly as a scheduled job.

**Comment by fredrikhgrelland** [comment]
Should we limit the tests and implement scheduled matrixes?

**Comment by zhenik** [comment]
> Should we limit the tests and implement scheduled matrixes?

Let's discuss it next meeting

**Comment by Neha-Sinha2305** [comment]
[Performance of GitHub-hosted macOS runner](https://github.com/actions/virtual-environments/issues/1336)

**Comment by zhenik** [comment]
The only reason that we use `macOs` is that OS has pre-installed `vagrant` [relevant issue](https://github.com/actions/virtual-environments/issues/433). Might be useful to have `vagrant` in linix-latest.
