### ISSUE TITLE
Build a MinIO terraform module with newest version of template

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#205]
Goal: document all issues discovered along the way.

Will use template as the backbone for a new repo that should do the following:

- Build a MinIO docker image
- Use and test this image within the hashistack eco-system
- Be possible to import this repo as its own terraform-module in use for other modules (for example be able to use this module together with a presto module)

Started this process here: https://github.com/pdmthorsrud/TF_MinIO/

**Comment by zhenik** [comment]
Another example: https://github.com/zhenik/terraform-nomad-minio1

**Comment by pdmthorsrud** [comment]
Update from me: I've gone through most steps of creating a terraform-module, but not the last part of making the terraform module generic and easy to use as an imported module in other modules. Will put this task on hold while doing some other stuff. 
Nikita will make a new MinIO module as he linked above!

**Comment by zhenik** [comment]
We keep work on it here: https://github.com/fredrikhgrelland/terraform-nomad-minio
