### ISSUE TITLE
Where should the README for the terraform-module be put?

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#206]
The README for a TF-module should be in root, but we have our own README already. Following the principle of wanting to not edit or remove existing files, the current approach isn't very clean. 
![image](https://user-images.githubusercontent.com/51820995/90385192-09ebb000-e083-11ea-8a33-1a920911aa31.png)

**Comment by fredrikhgrelland** [comment]
Hmm. I think it makes sense to have it as README.md still, but the first thing you do is to Change it for your own. Maybe we should add a TEMPLATE_README.md, providing a starting point for a good README ?

**Comment by pdmthorsrud** [comment]
> Hmm. I think it makes sense to have it as README.md still, but the first thing you do is to Change it for your own. Maybe we should add a TEMPLATE_README.md, providing a starting point for a good README ?

I agree having it as README.md because it makes a lot of sense when cloning template. 
We could have these steps:
- Rename `README.md` to `ISeriouslyCantComeUpWithAName.md` (obviously find a proper name)
- Rename `TEMPLATE_README.md` to `README.md` and add whatever to suit your needs.

But this would cause problems if you ever want to rebase to update you repo. What about calling the current `README.md` something else, and have a line at the top of `README.md` that points to the template´s  README

**Comment by zhenik** [comment]
I would suggest:

```
badge: build-on - vagrant-hashistack link

# Title (terraform-nomad-<module_core>)

## Terraform versions compatability

## Features

## Usage
  ### requirements 
  ### providers
  ### inputs
  ### outputs
## Best practices

## Examples

## Authors

## Code of conduct

## License 

```
