### ISSUE TITLE
Using `vagrant up --provision` makes playbook fail

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#212]
Fails because local_test is undefined.
![image](https://user-images.githubusercontent.com/51820995/90403039-a4a6b780-e0a0-11ea-8291-e48d38c582dd.png)

Not sure if we'd like it to work or not. But if we want to enforce that all actions should be started via the Makefile I believe we should actually add a docker-build command like I've proposed earlier.

**Comment by pdmthorsrud** [comment]
Removing the bug-tag, isn't necessarily a bug

**Comment by zhenik** [comment]
Solved by usage section [here](https://github.com/fredrikhgrelland/vagrant-hashistack#option-1-starting-a-plain-default-box)
