### ISSUE TITLE
Rethink how we sync https://github.com/fredrikhgrelland/vagrant-hashistack-template

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#217]
# Idea

- Sync on PR in parent to a separate branch. Will run tests in template automatically. Allows template development at same pace.

**Comment by zhenik** [comment]
## Problem
Once user creates new repository from template, that new repository has no common git-history with original template. 

## How to resolve
Originally posted [here](https://github.com/fredrikhgrelland/terraform-nomad-minio/pull/9#issue-476234355)

Basically  **git merge**.

```
1. Add remote upstream to template origin
2. Fetch all
3. checkout new branch from master
4. Run git merge with the flag `--allow-unrelated-histories` 
5. fix conflicts
6. commit
7. PR against current master
```
[ref stackoverflow](https://stackoverflow.com/a/56577320)

**Comment by zhenik** [comment]
continue #207

**Comment by zhenik** [comment]
Comments

# Rethink sync `template -> module`

- in module github actions which trigger sync (PR against itself) with original template



# Rethink sync `box -> template`

## 1. When release (easy)

### Problem  
- personal access token
- missing git history ()

## 2. Make rutine (PR) in own branch to template

**Comment by zhenik** [comment]
Example try https://github.com/zhenik/repo
