### ISSUE TITLE
Template Vagrantfile wrong paths

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#218]
https://github.com/fredrikhgrelland/vagrant-hashistack-template/runs/994196486#step:8:214

**Comment by Neha-Sinha2305** [comment]
In order to get this **`playbook` does not exist on the guest: /vagrant/ansible/playbook.yml** working locally, i modified the *ansible.provisioning_path* to */vagrant/dev/ansible* as that's the location where i have placed my run_terraform.yml file.

Is that the correct way?
