### ISSUE TITLE
Test PR for CHANGELOG.md changes

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#220]
We are constantly missing the mark on adding changelog to our PRs. It is considered an afterthought.
We should change this by adding a test in github actions. Any PR must **touch** the CHANGELOG.md file.

**Comment by fredrikhgrelland** [comment]
@Neha-Sinha2305 Assigned you on this. Up for it?

**Comment by Neha-Sinha2305** [comment]
Sure! Will give this a try :+1
