### ISSUE TITLE
Add workflow to sync templated repo from upstream on a schedule

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#222]
https://github.com/narrowspark/template-sync-action

**Comment by zhenik** [comment]
Suggestion for each module that is created with the template:
1. rename branch `master` to `upstream` and leave it untouchable, only for sync with vagrant-hashistack-template
2. make new branch which is going to be the default branch

Once the original template is updated, the developer of the module decides the necessity of `rebase` 
`upstream` -> `default`

**Comment by zhenik** [comment]
@fredrikhgrelland can you elaborate more why it should be done on schedule?

**Comment by Neha-Sinha2305** [comment]
I would go with Option 1:
```
Use concrete linter version in original template instead of latest (bump periodically)
https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/.github/workflows/on_pr_master.yml#L37
```

**Comment by fredrikhgrelland** [comment]
Option 1 is always be the right one.

**Comment by fredrikhgrelland** [comment]
This is irrelevant becuase of #331 closing
