### ISSUE TITLE
Add description to `template/example/README.md` 

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#228]
It's just an empty doc atm. Should have an explanation of what should be here, and how to use itt. This doc should also be linked from the main README.md as well

**Comment by zhenik** [comment]
Do you @pdmthorsrud  mean this one `vagrant-hashistack/template/example/README.md`?

**Comment by pdmthorsrud** [comment]
Yup, you're correct. Don't know why I wrote `terraform/`, sorry about that.
