### ISSUE TITLE
Using VMWare together with vagrant

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#235]
Got this sent to me by Ole Andre, wanted to put it up here in case some of you haven't seen it!

https://www.idkrtm.com/how-to-use-vagrant-with-vmware-vcenter/

**Comment by fredrikhgrelland** [comment]
I will do some investigations.

**Comment by zhenik** [comment]
@fredrikhgrelland any updates?

**Comment by fredrikhgrelland** [comment]
I think we should leave this. It requires a lot of work and basically requires manual intervention and two separate build processes.
