### ISSUE TITLE
'If you are behind a transparent proxy' information should be placed in the 'Prerequisites' section

### ISSUE THREAD

**Issue by Neha-Sinha2305** [fredrikhgrelland/vagrant-hashistack#254]
New users of **vagrant-hashistack box** tend to run into the issue of certificates when they are behind a transparent proxy  and run the **make install** command. It would be better user experience if we can make this more intuitive for them:

1. Move the section that speaks about transparent proxy in the Prerequisite section before the **make install** command info
OR
2. When the make install command fails due to the proxy issue then provide the link to the section: **If you are behind a transparent proxy**  in the error message 
OR
3. Automatically set the environment variables

Whichever of the above three is viable can be implemented

**Comment by zhenik** [comment]
#257 merge does only 1st step.
