### ISSUE TITLE
Mirror look'n'feel of parent repo README.md to template repository

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#259]
Cube image to use https://www.svgrepo.com/download/58111/cube.svg or https://www.svgrepo.com/download/75570/cube.svg

**Comment by zhenik** [comment]
>Add link to it in a separate `docs/acknowledgements.md`

Can you elaborate, what do you mean by separate `docs/acknowledgements.md`?

**Comment by pdmthorsrud** [comment]
Do you mean we should download it, and have an `acknowledgements.md` that mentions all our sources?
