### ISSUE TITLE
How to expand resources in Vagrantfile [new section in template/README.md]

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#266]
During the development of the new module, I faced with an error in Nomad
```
Dimension memory exhausted on 1 node
```

I had to change memory from 2048 to 4096 `template/Vagrantfile`
```
vb.memory = 4096
```

[Similar issue](https://github.com/hashicorp/nomad/issues/1732)

**Comment by Neha-Sinha2305** [comment]
@zhenik : Will it make sense to add a FAQ section at the bottom of the README and add this info there?
For example:
![faq-section](https://user-images.githubusercontent.com/67954397/91296566-1e275f80-e79d-11ea-894b-271edd930377.png)

**Comment by zhenik** [comment]
@Neha-Sinha2305 Seems good. Pay attention to default resources (AFAIR its 1 cpu and 1024 RAM) and cpu resource. Link ref https://www.vagrantup.com/docs/providers/virtualbox/configuration.html#vboxmanage-customizations

**Comment by pdmthorsrud** [comment]
Shouldn't this actually just be a section under `Configuration`?

**Comment by pdmthorsrud** [comment]
https://github.com/fredrikhgrelland/vagrant-hashistack/pull/278#issuecomment-681688952
