### ISSUE TITLE
Add cheat sheet for CLIs (vagrant, nomad, consul, terraform, vault)

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#268]
Do we need it @fredrikhgrelland @Neha-Sinha2305 @pdmthorsrud ? If not, let us close the issue

Just an idea to have useful commands in simplified representation somewhere in the current repository. 
Example https://github.com/zhenik/doc-fix/blob/master/docs/addtional/vagrant_cheat_sheet.md

`NB` If YES, make reference in documentation.

**Comment by pdmthorsrud** [comment]
I wanna say most people end up looking at google anyways, __but__ it's difficult to look up on google when you don't know what you're looking for. I personally can't see any reason why it would _negatively_ affect anything adding it in, except maybe the need to maintain it in the future as new features are added.

**Comment by zhenik** [comment]
I would suggest also expand this idea to `terraform`, `consul` and `nomad` CLIs also

**Comment by Neha-Sinha2305** [comment]
@zhenik : Can we change the milestone for this issue to 0.3.3? We can aim to release 0.3.2 by eod then!
