### ISSUE TITLE
Strict naming convention for domain features [example - toggles/switches functionality] 

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#269]
I would like to suggest to give once-&-forever proper name for box functionality.

Example in README.md, [configuration toggles/switches](https://github.com/fredrikhgrelland/vagrant-hashistack#configuration)

What we chose:
- [ ] Configuration **toggle**
- [x] Configuration **swich** <= we chose, as far as I understand from discussion

[originally asked](https://github.com/fredrikhgrelland/vagrant-hashistack/pull/267#discussion_r476380907)

**Comment by zhenik** [comment]
## Suggestion
In #267 this functionality named as `Configuration switches`.
Could you @Neha-Sinha2305 @pdmthorsrud @fredrikhgrelland confirm to use this name in the future and we close this issue? (No more `toggles`)

**Comment by pdmthorsrud** [comment]
Hmm.. A toggle is always between two things, a switch _could_ switch between several things. I imagine a future where each env-variable might switch between more than `true` and `false`, so `Switch` is more appropriate
