### ISSUE TITLE
How to release template

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#270]
Initially asked by @pdmthorsrud -> https://github.com/fredrikhgrelland/vagrant-hashistack/pull/267#discussion_r476492244 

Partly automated https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/.github/workflows/on_release.yml#L23-L26

**Comment by zhenik** [comment]
@fredrikhgrelland could you elaborate how this triggered?

**Comment by fredrikhgrelland** [comment]
This is triggered by manually editing the release ( without any changes )

**Comment by zhenik** [comment]
First template release [#7](https://github.com/fredrikhgrelland/vagrant-hashistack-template/pull/7)
