### ISSUE TITLE
Template `make example` missunderstanding

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#271]
## Problem
`make example` command is running `test_example`.

There is a naming collision. `template/` directory contains two directories:
```
test_example/
example/
```
Where `test_example/` is just an example of how to use the template when `example/` is an example of how to run terrafom module which lies in the root.

Currently, the command `make dev` runs terraform module which locates in `example/`

## How to fix
Option 1:
Rename `make example` to `make run-template-example` or smth similar

Option 2:
....

**Comment by pdmthorsrud** [comment]
I say we rename it to make template_example :) Note: In #267 `test_example` is renamed to `template_example`

**Comment by Neha-Sinha2305** [comment]
@zhenik : Can we close this?

**Comment by zhenik** [comment]
The command `make example` is still controversial to me to understand which example it runs https://github.com/fredrikhgrelland/vagrant-hashistack/blob/template-doc-refactor/template/Makefile#L31

**Comment by pdmthorsrud** [comment]
Yeah, it's still just `make example`. I haven't changed it bexause there is no "consesus" here yet. But I mean, we two agree, let's just change it?

**Comment by Neha-Sinha2305** [comment]
> @pdmthorsrud I see that directory waas renamed :+1 , but command is not changed in #267
> 
> @Neha-Sinha2305
> The command in template/ folder `make example` is still controversial to me to understand which example it runs https://github.com/fredrikhgrelland/vagrant-hashistack/blob/template-doc-refactor/template/Makefile#L31

Hmm..i get it and surely we should solve this.
 I was just wondering if it will be better to add new issues tagged for milestone 0.3.3 instead of 0.3.2, more so for issues that need consensus or discussion. 0.3.2 aims to improve the basic documentation and i guess we have achieved that through the PRs that are already merged so we could focus on releasing these changes so as to keep the momentum going :)

**Comment by zhenik** [comment]
Yeah, I will mark it for 0.3.3
