### ISSUE TITLE
Add a "Get Started" section

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#272]
Should be fairly quick and simple (Imagine Tor Eivind (a data scientist), and Per Daniel (a developer that sets up infrastructure)), but also give pointers to those advanced enough to want more.

> Hm, I agree with this, but there will be a full "how-to" later, so I think it's better to put it in that PR

_Originally posted by @pdmthorsrud in https://github.com/fredrikhgrelland/vagrant-hashistack/pull/267#discussion_r477144673_

**Comment by pdmthorsrud** [comment]
How tos:
* Build docker image
* Make available on minio
* nomad-job definition
    * also how to consul-connect
    * how to integrate with vault
* deploy with terraform

**Comment by zhenik** [comment]
#268 related

**Comment by zhenik** [comment]
@pdmthorsrud can you move this issue to `vagrant-hasihstack-template`

**Comment by pdmthorsrud** [comment]
Will do!
