### ISSUE TITLE
Open port requirements on local machine

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#274]
I would like to suggest adding the documentation section about `Open port requirements on local machine`.

Usecase: 
GItlab runner (its vm image) will use `vagrant-hashistack`

**Comment by fredrikhgrelland** [comment]
Yes, we can clarify this default here: https://github.com/fredrikhgrelland/vagrant-hashistack#services by referencing a new section here https://github.com/fredrikhgrelland/vagrant-hashistack#option-2---config-files explaining how to change it using Vagrantfile. Also needed here https://github.com/fredrikhgrelland/vagrant-hashistack/tree/master/template#vagrant-box-resources

**Comment by fredrikhgrelland** [comment]
Also: https://github.com/fredrikhgrelland/vagrant-hashistack/issues/289

**Comment by zhenik** [comment]
## TODO
- [ ] update doc, give user info that port-mapping can be changes https://github.com/fredrikhgrelland/vagrant-hashistack/blob/e5e86b8e6b64b86e6be67f167eae321eae91287a/packer/Vagrantfile#L5-L10
- [ ] auto_coorect feature #289
