### ISSUE TITLE
Increase timeout [Task - Archive docker image]

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#279]
## Problem with task: Archive docker image

The pipeline is failing https://github.com/fredrikhgrelland/terraform-nomad-hive/pull/1/checks?check_run_id=1036134913#step:8:402 

Each run failures happens in different workflows.

@fredrikhgrelland have a theory that it due to slow I/O which can be reason reaching timeout. 

## Potential solution
Increase timeout from 60s to 120s.

**Comment by fredrikhgrelland** [comment]
increse http_timeout 60 -> 120
