### ISSUE TITLE
Add section to template README "Nomad ACL handling"

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#281]
In `template_example` we use [nomad_acl_test.tf](template/template_example/example/nomad_acl_test.tf) to generically work with both acl enabled and disabled in nomad. This needs to be documented for new users creating a terraform module (remember to remind them to include `variables.tf`).

**Comment by fredrikhgrelland** [comment]
Yes.... maybe we should have this file as default in the actual template?

**Comment by pdmthorsrud** [comment]
Yeah, that might be just as well, together with #290 and a dir called `vagrant-box` or something to signalise this is how it's used together with the vagrant-box that might be fairly intuitive
