### ISSUE TITLE
Add an example of .env-file in template

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#291]
There's no example on how to define the variables in `.env`, we need that. Preferably added to doc I believe. Having a `.env` that's edited will be cumbersome whenever you update your own repo with a new release of template

**Comment by zhenik** [comment]
Exists in `template_example` https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/template/template_example/.env
