### ISSUE TITLE
http_timeout will be deprecated, must be changed to build.http_timeout

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#293]
![image](https://user-images.githubusercontent.com/51820995/91484448-82cfe080-e8a9-11ea-98aa-bbcd629a6f7f.png)

**Comment by zhenik** [comment]
https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/template/template_example/dev/ansible/01_build_docker_image.yml#L29-L35

**Comment by zhenik** [comment]
Closes by [#1](https://github.com/fredrikhgrelland/vagrant-hashistack-template/issues/1)
