### ISSUE TITLE
Update labels description

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#310]
- [ ] refactor labels [idea in nomadproject](https://github.com/hashicorp/nomad/labels)
- [ ] description

**Comment by Neha-Sinha2305** [comment]
@pdmthorsrud : Should we add one more label that says "blocked" or "Waiting for fix"? 
For example, I cannot proceed with fixing this issue : #312 before https://github.com/github/super-linter/issues/708 is fixed.

**Comment by pdmthorsrud** [comment]
> @pdmthorsrud : Should we add one more label that says "blocked" or "Waiting for fix"?
> For example, I cannot proceed with fixing this issue : #312 before [github/super-linter#708](https://github.com/github/super-linter/issues/708) is fixed.

Yup, I agree with that.

**Comment by pdmthorsrud** [comment]
I'm also keeping this open for a little while to see how the labels are working. Having the "same" colour for the categories might be stupid, but I want to try it

**Comment by Neha-Sinha2305** [comment]
@pdmthorsrud : This workflow file needs to be updated as the labels have been updated: https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/.github/workflows/on_pr_master.yml

**Comment by pdmthorsrud** [comment]
> @pdmthorsrud : This workflow file needs to be updated as the labels have been updated: https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/.github/workflows/on_pr_master.yml

Oh shoot, thank you so much! Fixed in #318
