### ISSUE TITLE
Stick to the concrete linter version

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#312]
Originally posted [here](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/222#issuecomment-690084956)

**Comment by Neha-Sinha2305** [comment]
@zhenik :Which version of super-linter should we use?
https://github.com/github/super-linter/releases

**Comment by zhenik** [comment]
hot-fix solution from @Neha-Sinha2305 https://github.com/Neha-Sinha2305/terraform-nomad-presto/blob/8fcf9d4771ac595f5ba802a38e954e740ed34c02/.github/workflows/on_pr_push_master.yml#L15

**Comment by Neha-Sinha2305** [comment]
@zhenik : Should i include this hotfix solution in these files too to have a consistent implementation for now:

- [ ] https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/template/.github/workflows/on_pr_push_master.yml

- [ ] https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/.github/workflows/on_pr_master.yml

Note: Risk of not doing this will be that the hotfix in submodules will get overriden once we resynch the submodules with vagarant-hashistack-template latest code.

**Comment by zhenik** [comment]
I would suggest to do not add it. Modules maintainers will know it by new PR :) Believe me, like me here https://github.com/fredrikhgrelland/terraform-nomad-presto/pull/9

**Comment by Neha-Sinha2305** [comment]
> I would suggest to do not add it. Modules maintainers will know it by new PR :) Believe me, like me here [fredrikhgrelland/terraform-nomad-presto#9](https://github.com/fredrikhgrelland/terraform-nomad-presto/pull/9)

sure..i will pick up some other task then.
I will get back to this issue when  github/super-linter#708 is fixed.

**Comment by pdmthorsrud** [comment]
set this to 3
https://github.com/fredrikhgrelland/vagrant-hashistack/blob/7431a7f905f253a7b5eb143c59c07bd0ef30eb7a/.github/workflows/on_pr_master.yml#L42
