### ISSUE TITLE
Add version description on vagrantbox

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#32]
Link to changelog and maybe extract?

**Comment by zhenik** [comment]
I would also suggest changing the text `CD/CI` to the latest release `0.0.5`?

<img width="1259" alt="Screenshot 2020-06-16 at 15 15 33" src="https://user-images.githubusercontent.com/15572799/84779240-70514500-afe4-11ea-8080-a97ca883f5b4.png">

**Comment by fredrikhgrelland** [comment]
Do you know if that is possible to automate?

**Comment by zhenik** [comment]
Vagrant cloud does not have badges support. So, I would suggest adding in release action a new  commit to update text accordingly new version.

Other examples:
* ruby gem [Vagrant_cloud](https://github.com/hashicorp/vagrant_cloud)
* maven release [kafka-connect-common](https://github.com/lensesio/kafka-connect-common)

Another solution is to customize badge, [reference](https://github.com/marketplace?query=badge&type=actions).

**Comment by zhenik** [comment]
> Link to changelog and maybe extract?

I think links to `CHANGELOG` and `milestones` are best (IMHO)

**Comment by fredrikhgrelland** [comment]
https://github.com/marketplace/actions/changelog-reader
shields.io

**Comment by zhenik** [comment]
> https://github.com/marketplace/actions/changelog-reader
> shields.io

Requirements:
- Follow changelog format from [keepachangelog.com](https://keepachangelog.com/en/1.0.0/) 

ref: 
- [Change-log doc](https://github.com/mindsers/changelog-reader-action/blob/master/CHANGELOG.md)

**Comment by zhenik** [comment]
CHANGELOG.md formating fixing in https://github.com/fredrikhgrelland/vagrant-hashistack/pull/58
