### ISSUE TITLE
Add a target to makefile to run super-linter

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#321]
We use [super-linter](https://github.com/github/super-linter) on all PRs. We should add some targets to the `Makefile`s to run it locally.

**Comment by zhenik** [comment]
I think it was fixed. 
https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/template/Makefile#L17-L18

**Comment by zhenik** [comment]
@pdmthorsrud can we close this issue?

**Comment by pdmthorsrud** [comment]
You're totally right, Claes actually fixed this in #309. Sorry!
