### ISSUE TITLE
[UserStory] As a machine-user or normal-user of the box I expect the box not to fail because of convenience features.

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#322]
Original issue name: Add a switch somehow to turn port forwarding off or enable autocorrect when running in a shared CI runner.

port-forwarding to a local machine must be considered a convenience feature since it is not necessary for the box to function as designed. We should not fail a test or attempt to start a box because of port collision without giving clear directions on how to proceed. Preferably it is self healing ( as this is needed for machine-users )

When running in a shared CI environment, boxes will fail to start because of port collision. We should add documentation on how to turn port forwarding completely off by changing the ~/.Vagrant.d/Vagrantfile or we should add an environment switch or something.

We could even enable auto_correct by default and make it extremely visible for the user. I currently find myself wanting two vagrant-hashistack based boxes running at the same time, so I would love something that did not require me to change anything. Option 1. Would suit that scenario as well.

__Originally posted by @fredrikhgrelland in https://github.com/fredrikhgrelland/vagrant-hashistack/pull/320#issuecomment-691416603_

**Comment by pdmthorsrud** [comment]
If you find yourself wanting two up at once I agree we should either add switch, or enable auto_correct by default. But yeah, we need to make it very visible if we do https://github.com/fredrikhgrelland/vagrant-hashistack/pull/320#issue-485070723

**Comment by fredrikhgrelland** [comment]
Yeah, also I imagine two or more vagrantboxes forming an actual cluster at some point.

**Comment by fredrikhgrelland** [comment]
Added this to milestone as we need this to work somehow in a shared runner env.

**Comment by pdmthorsrud** [comment]
Duplicate #365
