### ISSUE TITLE
Bump versions require a new releases 

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#325]
PATCH || MINOR? -> update version require a new release.

!!! Raise conversation next time we bump versions, please. @zhenik @claesgill @fredrikhgrelland @pdmthorsrud @dangernil @Neha-Sinha2305

**Comment by fredrikhgrelland** [comment]
@zhenik Sorry, but I am not sure what you are trying to say/accomplish here? Did we do something wrong?

**Comment by zhenik** [comment]
> @zhenik Sorry, but I am not sure what you are trying to say/accomplish here? Did we do something wrong?

@Neha-Sinha2305 rised a question that once we bump version, these new versions could contain incompatibilities or breaking changes. We think that best way to control behavior such a behavior is to make either PATH or MINOR release of vagrant-hashistack after bumping version

**Comment by fredrikhgrelland** [comment]
Yes this is the smart thing to do. Should we document this anywhere and close this issue?

**Comment by Neha-Sinha2305** [comment]
I guess we can document this in [CONTRIBUTING.md#release-proces](https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/docs/CONTRIBUTING.md#release-process) and can also add comment/note in this file [variables.yml](https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/ansible/group_vars/all/variables.yml) so we would remember to follow the process.
