### ISSUE TITLE
Enable debug logs for github actions

### ISSUE THREAD

**Issue by Neha-Sinha2305** [fredrikhgrelland/vagrant-hashistack#329]
In the process of releasing [0.4.1](https://github.com/fredrikhgrelland/vagrant-hashistack/pull/328), we noticed that the following github action [semver-release-action](https://github.com/fredrikhgrelland/vagrant-hashistack/runs/1111332600?check_suite_focus=true) failed and it wasn't easy to pin-point the problem based on the error message that was printed:
```
  Run zwaldowski/semver-release-action@v11s
    github_token: ***
Run zwaldowski/semver-release-action@v1
  with:
    dry_run: true
    bump: pr/patch
    github_token: ***
##[error]Cannot read property 'toString' of null
```
It would be nicer if we could get better logs so that the problem becomes evident and takes lesser time to fix.
We might like to look at the information available in this page : https://github.com/actions/toolkit/blob/master/docs/action-debugging.md

**Comment by fredrikhgrelland** [comment]
We can enable debug logs by setting an env variable. We will only do this if there is a problem.
Closing this task as there is nothing we can do atm.
