### ISSUE TITLE
Outdated links in CHANGELOG.md

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#334]
## Description
Some of the links are outdated
- pointing to wrong locations
- pointing to files which do not exist anymore

## Example 1
- `startup.yml` file does not exist
- the link has a relative pass, but changelog is published in [vagrant-cloud](https://app.vagrantup.com/fredrikhgrelland/boxes/hashistack)

```text
## [0.1.0] - 2020-06-22

### Changed
...
- [startup.yml](ansible/start_hashistack.yml) waits until all services are up
```

## Example 2

```text
### Added
- the link has a relative pass, but changelog is published in [vagrant-cloud]
- directory was `test_example` was renamed to `test_example` in late releases
...
- Added healthchecks to the [countdash-job](template/test_example/conf/nomad/countdash.hcl).
...
## [0.2.2]
```

## Solution 1
- Do not use a relative path, use `http` links instead
- Use clean text instead of links

**Comment by pdmthorsrud** [comment]
Does it matter that they do not link anymore? It also says in the changelog that vagrant-hashistack and the template have been separated. If we change the changelog we "change the history" which we shouldn't do.

**Comment by zhenik** [comment]
Yeah, you are right. We can not change what was released, but at least we can avoid relative  links (or links in general)

**Comment by pdmthorsrud** [comment]
> Yeah, you are right. We can not change what was released, but at least we can avoid relative links (or links in general)

Aha, so this was more as info?

**Comment by zhenik** [comment]
> > Yeah, you are right. We can not change what was released, but at least we can avoid relative links (or links in general)
> 
> Aha, so this was more as info?

And a discussion. I published `solution 1` above, maybe you could bring another offer(s)

**Comment by pdmthorsrud** [comment]
> And a discussion. I published `solution 1` above, maybe you could bring another offer(s)

Sorry, I thought you meant that was a solution to the already existing links. I think we should use http-links. It's very useful to quickly see what files have been changed and go straight to them. Outdated links will happen of course, but we can live with that I feel like
