### ISSUE TITLE
Change output from the ansible-task running pre and poststart books in bootstrap.yml

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#335]
![image](https://user-images.githubusercontent.com/51820995/93344882-7c8ead80-f832-11ea-93c8-699972bcd711.png)
Right now it is printed a warning if there aren't any books. This should rather print something informative like "You can put books in `path` to run before or after startup".

Solution:
- Add a check in the ansible-task `Running poststart books` in `bootstrap.yml`

**Comment by dangernil** [comment]
I can't seem to replicate the WARNING issue, marking as invalid for now.

**Comment by pdmthorsrud** [comment]
Just adding to this, the warning is present if you do not have the pre_bootstrap or post_boostrap folders. Both are default in all clones of the template, so I am closing this issue.
