### ISSUE TITLE
Decouple template tasks and box tasks

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#336]
Running the box with `vagrant init fredrikhgrelland/vagrant-hashistack` and `ANSIBLE_ARGS='--extra-vars "local_test=true"' vagrant up --provision`does indeed work, but a lot the things done in `bootstrap.yml` is intimately connected to the template´s directories and general structure. For example the environment variables, or the pre and poststart books.

We could potentially separate this further so that running the box without any modifications will give you a working hashistack ecosystem without all the features we have added using the template.

What do you all think, should it be as connected as it is right now, or should we look into separating further sometime soon?

**Comment by fredrikhgrelland** [comment]
Yes, This makes sense.

**Comment by pdmthorsrud** [comment]
Closing this, redesign with 0.6.0 did introduce this
