### ISSUE TITLE
Project and issues-tab, what are their roles?

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#338]
Spørsmål om projects og labels:

ATM føler jeg de overlapper på noen ting (eksempel: label thinking/needs-discussion og column requirement-phase), som ikke følger DRY (to steder å maintaine). Hvor ønsker dere at vi mainly oppholder oss mens vi jobber: I issues tab til repos, eller i project? For meg er det vanskelig å skjønne hvilken rolle hver enkelt fyller.

Jeg liker issues-taben da det er lett å se alle issues og ha en god oversikt (som utvikler!) over relevant informasjon, men skjønner at vi trenger en lettere og tydeligere oversikt over hva som skjer fra et overordnet blikk over alle repos. Hva med å bruke noe [slikt](https://github.com/philschatz/project-bot) for å automatisere vedlikeholdet av project-siden ved hjelp av labels, og sikte mot at alt av oppdatering og maintaining av issues blir gjort i issue-tab som utvikler? 

Tanker?

ENGLISH:
~This was originally written as a question in the teamchat, but realised it got a little long, so I decided to create an issue. I will translate this to english tomorrow!~

ATM I feel like they are overlapping in some places (example: label thinking/needs-discussion and the column "requirement-phase"). This ends up being to places to maintain. Where should we keep our workflow: mainly in the issues tab, or in the project? I'm struggling to see what role each fills right now. 

I like the issue tab for working with and maintaining the issues (day to day as developer), but realise the project will give us a much needed overview of all repos. I think we should use something like [project-bot](https://github.com/philschatz/project-bot) to automate the maintenance of the project-board, and aim to use the issues-tab for the general "working with issues".

**Comment by claesgill** [comment]
I think this is an important question, and that we should book a meeting to discuss this topic.

**Comment by Neha-Sinha2305** [comment]
I have modified column namesy, reordered and have added short notes for each of the columns: https://github.com/users/fredrikhgrelland/projects/1.
We could discuss this in the next weekly meeting and see if this is helpful.

**Comment by pdmthorsrud** [comment]
Also, I want to add [project-bot](https://github.com/philschatz/project-bot). I tried using this in a private repo a few days back, didn't work. Only tried for half an hour or so, it's possible I did something wrong.

**Comment by Neha-Sinha2305** [comment]
[project-bot](https://github.com/philschatz/project-bot) looks cool. We surely can give it a try, i will have quick look.
May be it needs the project board to be set to **public**.
I wonder why our project board is set to **Private**, i guess we could turn it into public and restrict access for who can edit it.
For example, this project board [vagrant-hashicorp](https://github.com/hashicorp/vagrant/projects/1) is public with restricted write access.

**Comment by Neha-Sinha2305** [comment]
> Also, I want to add [project-bot](https://github.com/philschatz/project-bot). I tried using this in a private repo a few days back, didn't work. Only tried for half an hour or so, it's possible I did something wrong.

Looks like the bot has issue [Label filter and new_issue not working](https://github.com/philschatz/project-bot/issues/79)

**Comment by pdmthorsrud** [comment]
> [project-bot](https://github.com/philschatz/project-bot) looks cool. We surely can give it a try. I will have a quick look.
> May be it needs the project board to be set to **public**.
> I wonder why our project board is set to **Private**, i guess we could turn it into public and restrict access for who can edit it.
> For example, this project board [vagrant-hashicorp](https://github.com/hashicorp/vagrant/projects/1) is public with restricted write access.

Nah, my project was public, so it wasn't that. Also, Fredrik needs to be the one who installs the plugin. 

Yeah, I did see that issue, tried what the last guy commented, didn't work. No new issues with similar problems since that one either
