### ISSUE TITLE
Open consul connect proxies from inside the box, and forward this to the user's machine

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#343]
Right now we open proxies from outside the box. Opening these inside the box would enable us to take advantage of everything the box brings (e.g. fetching consul acl token via vault which will be implemented in #342).

Requirements:
- Pattern for setting up consul-connect proxies to services
- These proxies are transparent for the user; the service is simply available as if the service is running on the user's machine locally (e.g. service is available on `localhost:5050``

**Comment by zhenik** [comment]
Does this cover your needs https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/dev/ansible/05_presto_create_tables.yml#L14-L28 ?

**Comment by pdmthorsrud** [comment]
> Does this cover your needs https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/dev/ansible/05_presto_create_tables.yml#L14-L28 ?

Is that service then available on `10.0.3.10:8888` for the user?

**Comment by zhenik** [comment]
> > Does this cover your needs https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/dev/ansible/05_presto_create_tables.yml#L14-L28 ?
> 
> Is that service then available on `10.0.3.10:8888` for the user? If so, I guess this would serve the correct purpose for now, yes.

I havent check outside the box.

**Comment by pdmthorsrud** [comment]
> > > Does this cover your needs https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/dev/ansible/05_presto_create_tables.yml#L14-L28 ?
> > 
> > 
> > Is that service then available on `10.0.3.10:8888` for the user? If so, I guess this would serve the correct purpose for now, yes.
> 
> I havent check outside the box.

We should check that, and if it is, we should document this, and make that the primary way of giving users access to the services (instead of having targets in the `Makefile` that opens new consul-connect proxies).

**Comment by zhenik** [comment]
So far, research results

# Option 1
Expose (to local machine), range of ports, which will be used for local-proxy inside the box.

1.1.
Reference https://www.vagrantup.com/docs/networking/forwarded_ports

You can define allowed port range assignable by Vagrant when port collision is detected via config.vm.usable_port_range property.

```
Vagrant.configure("2") do |config|
  config.vm.usable_port_range = 8000..8999
end
```

1.2.
Reference https://serverfault.com/a/581833

Using for-loop
```
for i in 64000..65535
    config.vm.network :forwarded_port, guest: i, host: i
end
```

# Option 2
Using vagrant cli

```
vagrant ssh -- -L <local machine port>:<host inside machine>:<port inside machine>

vagrant ssh -- -L 7001:localhost:5432
```

**Comment by zhenik** [comment]
I like option 2, available from the box. You can use it without any changes.
