### ISSUE TITLE
make 'update-submodule' does not work as expected

### ISSUE THREAD

**Issue by Neha-Sinha2305** [fredrikhgrelland/vagrant-hashistack#350]
### Steps to reproduce the issue:
1. Clone the **vagrant-hashistack** project
2. Run command **make update-submodule**

### Expected behavior:
**template** directory should get updated 

### Actual behavior:
Nothing happens

### Resolution:
Change the url in [.gitmodules](https://github.com/fredrikhgrelland/vagrant-hashistack/blob/f33100fc1f34712ba72711e390735701b35f6344/.gitmodules#L3) to :
```
url = https://github.com/fredrikhgrelland/vagrant-hashistack-template.git
```

**Comment by zhenik** [comment]
I want to notice that the first time you cloned a repository, it's not going to clone its submodules.
Current command in `Makefile` applied on existing submodule. 
```
update-submodule:
	git submodule update --remote
```

## Todo
Find an automate solution for it. might be
```
update-submodule:
        git submodule update --init
	git submodule update --remote
```

`?` verify that `git submodule update --init` idempotent command
