### ISSUE TITLE
Add section `version` to README

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#358]
## Version
| vagrant-hashistack | consul | nomad  | vault  | consul-template |
| ------------- |:-------------|:-------------|:-------------|:-------------|
| 0.4.3      | 1.8.4      |   0.12.4 |  1.5.3 |  0.25.1 | 
| 0.4.0      | 1.8.3 | 0.12.3 |1.5.2 | 0.25.1 |

Might need to expand columns. Also, having such a table either at the beginning or end of the documentation

**Comment by Neha-Sinha2305** [comment]
I guess it should also be a part of release notes?

**Comment by zhenik** [comment]
Only last version in README.md?
