### ISSUE TITLE
make install fails on new mac

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#362]
Error msg: 
![image](https://user-images.githubusercontent.com/51820995/94650554-cb652a00-02ab-11eb-8afd-2a75c2ec1d47.png)

Seems to be it's running 
https://github.com/fredrikhgrelland/vagrant-hashistack/blob/3a2dda3f46f06f84262f440782b150e2fbc3b970/install/Makefile#L17-L23
although `$OS` is not set. Virtualbox is already installed, which is why it doesn't fail on `vboxmanage`

**Comment by zhenik** [comment]
```
make[2]: Nothing to be done for `prereq'
```
Because you have already on ur machine `brew`


Not sure about the rest of log

**Comment by pdmthorsrud** [comment]
> Not sure about the rest of log

Yeah, that one works as expected! :)

**Comment by fredrikhgrelland** [comment]
@pdmthorsrud Is it a bug or not?

**Comment by pdmthorsrud** [comment]
> @pdmthorsrud Is it a bug or not?

Forgot this. It is indeed a bug. The problem was a wrong default goal in the mac's makefile. I'll make a PR real quick!
