### ISSUE TITLE
Easier way to override or update nomad/consul policies from modules

### ISSUE THREAD

**Issue by Neha-Sinha2305** [fredrikhgrelland/vagrant-hashistack#367]
While working on [Add host volume](https://github.com/fredrikhgrelland/terraform-nomad-minio/issues/20) to minio module, I needed to update the nomad write policy so as to include policies regarding host volume.
In my understanding, it wasn't that straight forward way to get the policy added as this has not been documented anywhere. 
I wonder if we could add some hooks in the box that could make it easier to override/update the policies similar to how we have added posibility to update the [hashistack configuration files](https://github.com/fredrikhgrelland/vagrant-hashistack-template/tree/master/dev/vagrant/conf#add-or-override-hashistack-configurations)

**Comment by pdmthorsrud** [comment]
This is possible. Uses consul post bootstrap folders, fixed from version 0.6.0.
