### ISSUE TITLE
Implement more granular box bootstrap overrides

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#370]
Current box implements configuration overrides https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/ansible/bootstrap.yml#L17, prestart books https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/ansible/bootstrap.yml#L33 and poststart books https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/ansible/bootstrap.yml#L154

bootstrap also implicitly assumes an immediate and sequential startup of consul, vault and nomad.

We need a finer granularity configuration and startup procedure in order to set tokens and policies for consul and vault before nomad starts up.

I am suggesting the following changes:

- [ ] Configure and startup singular services as a unit
 - 1. configuration override ( file copy )
 - 2. prestart procedure ( ansible )
 - 3. startup service ( ansible )
 - 4. poststart procedure ( ansible )
- [ ] Startup sequence should be configurable ( consul, vault, nomad) could be changed to ( vault, consul, nomad)

This will allow for the following scenario:
1. vault: startup
2. consul: prestart - apply switches for acl
3. consul: startup
4. consul: poststart - create namespace, policy and mint a namespaced token -> put in vault
5. nomad: prestart - aquire namespaced token from vault and create configuration file
6. nomad: startup
7. nomad: poststart - verify namespaced nomad.

**Comment by zhenik** [comment]
> - [ ] Configure and startup singular services as a unit
>  - 1. configuration override ( file copy )

Keep in mind, that vault does not support the feature `config files merge`

**Comment by zhenik** [comment]
Current impl

`pre` -> `consul > nomad > vault` startup> `post`

Needed impl (example)
`pre-vault -> vault -> post-vault` => `pre-consul -> consul -> post-consul` => `pre-nomad -> nomad -> post-nomad`
