### ISSUE TITLE
Why do we need reload of daemons in `ansible/install.yml`

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#371]
https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/ansible/install.yml#L60-L61

Questions:
Why do we need reload of daemons in the install script? We have not started anything yet

**Comment by pdmthorsrud** [comment]
When files are added to system, you need to reload to verify and add these files to everyone's knowlegde
