### ISSUE TITLE
Make it possible to run box with `vagrant up`

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#374]
Right now you need to add the tag local-test=true or run `--skip-tags test` to get past the env_override. Find a way to circumvent this.
Below is from a run with `vagrant up`
![image](https://user-images.githubusercontent.com/51820995/95078878-ae28c500-06ca-11eb-8d27-b815491a9cb6.png)

Offending lines: 
https://github.com/fredrikhgrelland/vagrant-hashistack/blob/47d38018a42aa57fbd99ee2e4c3d3b5c8fc70155/ansible/bootstrap.yml#L11-L15

**Comment by Neha-Sinha2305** [comment]
@pdmthorsrud : https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/README.md#option-1-starting-a-plain-default-box
Doesn't this address the problem you mentioned above?

**Comment by pdmthorsrud** [comment]
> @pdmthorsrud : https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/README.md#option-1-starting-a-plain-default-box
> 
> Doesn't this address the problem you mentioned above?

I dont think so. My point is that we have to pass ansible arguments to vagrant up. For clarity and user experience Id like to avoid that

**Comment by Neha-Sinha2305** [comment]
Looks like i have a fix for it ;) PR coming soon.
