### ISSUE TITLE
Add host_volume nomad policy

### ISSUE THREAD

**Issue by Neha-Sinha2305** [fredrikhgrelland/vagrant-hashistack#375]
Upstream changes to box. Refer https://github.com/fredrikhgrelland/terraform-nomad-minio/issues/32 for more details.

**Comment by zhenik** [comment]
I disagree. We might have these policies as an example in the context of https://github.com/fredrikhgrelland/vagrant-hashistack-template/issues/33  (Producer role). But it is not going to be the default policy.

**Comment by pdmthorsrud** [comment]
> @Neha-Sinha2305 I disagree. We might have these policies as an example in the context of [fredrikhgrelland/vagrant-hashistack-template#33](https://github.com/fredrikhgrelland/vagrant-hashistack-template/issues/33) (Producer role). But it is not going to be the default policy.

Would it not be OK if it is added to the default write policy that comes as an example with the box?

**Comment by zhenik** [comment]
It seems ok, just become implicit to the end-user of modules.
