### ISSUE TITLE
CI/CD label must show latest status of `master` branch

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#396]
## Problem
Label CD/CI shows latest status registered in Action. (Which is failing tests on PR). 

<img width="970" alt="Screenshot 2020-10-13 at 17 02 47" src="https://user-images.githubusercontent.com/15572799/95878959-18e69a00-0d76-11eb-9a1d-0826198d0af1.png">

## Expected behavior
Label CD/CI must show latest status registered in Action **of `master` branch**. (Not last registered run of PR)

**Comment by zhenik** [comment]
Issue is still relevant

**Comment by Neha-Sinha2305** [comment]
@zhenik : Some useful links : https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/adding-a-workflow-status-badge#using-the-branch-parameter

https://github.community/t/workflow-badge-no-status/17280
