### ISSUE TITLE
Missing ansible in makefile

### ISSUE THREAD

**Issue by m88614** [fredrikhgrelland/vagrant-hashistack#4]
Just realised we are missing an ansible installation in the makefile.

**Comment by fredrikhgrelland** [comment]
Why do you say that? Ansible is not necessry on the host, only the guest

**Comment by m88614** [comment]
I say that because I had to install ansible when I ran docker-hive's vagrantfile, so extrapolating from that I assumed it would be a dependency in this case as well, considering you use ansible in the same way. Am I way off track with my understanding here?

**Comment by fredrikhgrelland** [comment]
You are using the wrong provider, thats all. https://www.vagrantup.com/docs/provisioning/ansible_local is the right one ;)

**Comment by m88614** [comment]
Aha, `from the host` and `from the guest`, I see. Thank you.
