### ISSUE TITLE
Cancel previous action runs

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#423]
## Feature description
Cancel unneeded jobs from from github actions

## Why is it needed?
We get a ton of runs that are not necessary because of newer pushes/changes

## Suggestion(s)/solution(s) [Optional]
https://github.com/marketplace/actions/skip-duplicate-actions

## Definition of done
Cancel all previous jobs of branch if new changes are pushed

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [x] Added to milestone

**Comment by zhenik** [comment]
<img width="1442" alt="pipes" src="https://user-images.githubusercontent.com/15572799/96552841-a2d1be00-12b4-11eb-9a48-713d2746629c.png">
