### ISSUE TITLE
Add aliasing for vagrant binary including CA trust for internal transparent proxy

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#43]
`SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt vagrant`

**Comment by m88614** [comment]
@fredrikhgrelland, are you actually working on this? Asking because you said you were going to work on #20

**Comment by fredrikhgrelland** [comment]
No. Sorry. Not working on that

**Comment by m88614** [comment]
You mean something that runs `vagrant up` with the prefixes if you are behind a transparent proxy, correct?

**Comment by fredrikhgrelland** [comment]
I thought it might be possible to add an alias to bashrc when running make install. It could wrap vagrant with those environment variables. See first comment.

**Comment by m88614** [comment]
> I thought it might be possible to add an alias to bashrc when running make install. It could wrap vagrant with those environment variables. See first comment.

Can we assume everybody has the same path to the certificate-file? If not, they would have to go in and edit the source-code to make it work with their system if it's different. In that case only having the doc for transparent proxy is better IMO.
