### ISSUE TITLE
Nomad - Vault integration was removed [bug]

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#446]
## What is the issue?
I noticed that the previous Nomad-Vault integration was removed. I do not know was it accidentally or intended.  

PR -> https://github.com/fredrikhgrelland/vagrant-hashistack/pull/383/files

It is not a problem so far after a big refactor that was introduced in 0.7.0

Now, the user has control over each service configuration. 

[related to vagrant-hashistack-template] If you need to have integration between Nomad and Vault, just add to
`dev/vagrant/conf/nomad/` one more file `00-enable_vault.yml` with 
```yaml
vault {
  enabled = true
  token   = "master"
  address = "http://127.0.0.1:8200"
}
```
[Example with Postgres module](https://github.com/fredrikhgrelland/terraform-nomad-postgres/blob/master/dev/vagrant/conf/nomad/00-enable_vault.hcl)

## Suggestion(s)/solution(s) [Optional]
- [x] Provide default config with integration between Nomad and Vault. 
- [ ] Update doc example for `pre/post` how to override default config (especially this example).
- [x] Instead of `master` token, provide management token from Vault.

## Checklist (after created issue)
- [X] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by zhenik** [comment]
Put it back:
`+`
- integration from the box without any additional actions

`-`
- user want to test other tokens

Note:
1. Best example for `pre/post` config for hashicorp services (nomad here)

**Comment by fredrikhgrelland** [comment]
@zhenik I think we should put it back and provide example on how to override this specific configuration in the documentation.
