### ISSUE TITLE
Add skeleton project - **a starting point** - for using the vagrant box in a project for test and dev

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#83]
In addition to strong documentation on how to use the box and customize to fit the needs of a project, we could simplify the process of building a CI pipeline backed by `vagrant-hashistack` by adding a skeleton project.

### If put in a separate repo e.g. `vagrant-hashistack-template`
- 👍 Merging in changes directly whenever you would like to use new or changed features to the box.
- 👍 Less need to document what needs to happen if you move from one version to another as it is implicit in the diff.
- 👍 Fork the repository - quickstart.
- 👎 It requires cross repo PRs to be synced as well as release cadence.

### If put in a sub directory `/template/*/`
- 👍 We could add different templates for different needs. ( dev/test/demo)
- 👎 It will require a series of git commandline actions in order to be easily consumed and updated to new versions.
- 👍 All PRs will include any changes to templates. Simplify dev process.

**Comment by m88614** [comment]
Why would a skeleton project simplify the process of building a CI pipline? Do you mean in the same way the `test` dir is basically a template, and we can use that for testing before integrating changes?

Gut reaction is I'm for a `template` dir as long as we keep the templates to a minimal, and only (obviously) pertain to the development/testing/showing of the vagrant box built here. Cross repo PRs to be synced sounds like a nightmare to me.

**Comment by fredrikhgrelland** [comment]
inspiration: https://jrsmith3.github.io/merging-a-subdirectory-from-another-repo-via-git-subtree.html#:~:text=If%20you%20want%20only%20the,subdirectory%20in%20a%20target%20repo.

**Comment by fredrikhgrelland** [comment]
We will try to make use of both by adding bots #87 to do the heavy lifting while keeping the master in one place.

**Comment by fredrikhgrelland** [comment]
I'll create a simple base template and make a draft pr.
